import { test } from 'node:test';
import assert from 'node:assert/strict';
import { generatePayload } from '@paybysquare/core';
import { buildTestApp, VALID_INPUT } from './helpers.js';

test('POST /v1/payload returns the payload generated by core', async () => {
  const app = buildTestApp();
  const response = await app.inject({
    method: 'POST',
    url: '/v1/payload',
    payload: VALID_INPUT,
  });

  assert.equal(response.statusCode, 200);
  const body = response.json() as { payload: string };
  assert.match(body.payload, /^[0-9A-V]+$/);
  assert.equal(body.payload, generatePayload(VALID_INPUT));
  await app.close();
});

test('POST /v1/payload rejects invalid input with the field name', async () => {
  const app = buildTestApp();
  const response = await app.inject({
    method: 'POST',
    url: '/v1/payload',
    payload: { ...VALID_INPUT, iban: 'not-an-iban' },
  });

  assert.equal(response.statusCode, 400);
  const body = response.json() as { error: { message: string; field: string } };
  assert.equal(body.error.field, 'iban');
  assert.ok(body.error.message.length > 0);
  await app.close();
});

test('POST /v1/payload rejects a non YYYY-MM-DD date', async () => {
  const app = buildTestApp();
  const response = await app.inject({
    method: 'POST',
    url: '/v1/payload',
    payload: { ...VALID_INPUT, date: '01.06.2024' },
  });

  assert.equal(response.statusCode, 400);
  const body = response.json() as { error: { field: string } };
  assert.equal(body.error.field, 'date');
  await app.close();
});

test('POST /v1/payload works without optional date (core defaults to today)', async () => {
  const app = buildTestApp();
  const { date: _date, ...noDate } = VALID_INPUT;
  const response = await app.inject({
    method: 'POST',
    url: '/v1/payload',
    payload: noDate,
  });

  assert.equal(response.statusCode, 200);
  assert.match((response.json() as { payload: string }).payload, /^[0-9A-V]+$/);
  await app.close();
});
